name: Run Crawler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'  # KST 07:00
    - cron: '0 0 * * *'   # KST 09:00
    - cron: '0 2 * * *'   # KST 11:00
    - cron: '0 4 * * *'   # KST 13:00
    - cron: '0 6 * * *'   # KST 15:00
    - cron: '0 8 * * *'   # KST 17:00
    - cron: '0 10 * * *'  # KST 19:00
    - cron: '0 12 * * *'  # KST 21:00
jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Run crawler
        timeout-minutes: 4
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          DISCORD_ADMIN_WEBHOOK_URL: ${{ secrets.DISCORD_ADMIN_WEBHOOK_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python crawler.py 
